apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-api
  labels:
    app: chatbot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-api
  template:
    metadata:
      labels:
        app: chatbot-api
    spec:
      containers:
      - name: chatbot-api
        image: ai-sre-chatbot-api:latest
        imagePullPolicy: Never
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-sre-secrets
              key: OPENAI_API_KEY
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-api
spec:
  type: ClusterIP
  selector:
    app: chatbot-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
